PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
UsePAM yes
AllowUsers abc
AuthorizedKeysFile .ssh/authorized_keys
HostKey /var/lib/taltech-desktop/ssh/ssh_host_ed25519_key
HostKey /var/lib/taltech-desktop/ssh/ssh_host_rsa_key
