# This workflow is based on https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
name: "Build Docker images"
run-name: "Building Docker images on '${{ github.head_ref || github.ref }}'"

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: "Build Docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile_Focal
            tag: 20.04
          - dockerfile: Dockerfile_Jammy
            tag: 22.04
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}-${{ matrix.tag }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v3
        with:
          images: taltechivarlab/ubuntu-desktop
          flavor: |
            latest=auto
          tags: |
            type=sha,suffix=-${{ matrix.tag }}
            type=raw,value=${{ matrix.tag }},enable={{is_default_branch}}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}

      - name: Update description on Docker Hub
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: taltechivarlab/ubuntu-desktop
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
